### ISSUE TITLE
Sort objectives

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#25]
**Is your feature request related to a problem? Please describe.**
During community actions/objective management the order of the objectives is inconsistent and keeps changing after every update

**Describe the solution you'd like**
Sort the objectives by creation date, older ones last

**Describe alternatives you've considered**
Maybe allowing manual control over the order, maybe?

**Comment by lucca65** [comment]
@zacck

**Comment by zacck** [comment]
@GettyOrawo this is a super easy way of getting your hands dirty ...

**Comment by namoscagnm** [comment]
Hi, can you assign this to me?
Thank you!

**Comment by lucca65** [comment]
good luck @namoscagnm, this will mainly take you to understand and work with absinthe! be sure to check their documentation!

**Comment by namoscagnm** [comment]
Hi, I am new to graphql, but I managed to find the Objective class by querying:
{
  __schema {
    types {
      name
    }
  }
}
and I get an "Objective type" inside the response. 

I supposed that your problem arises when you query for a list of all responses?

I'm not sure its so, but I tried many commands, including:

After this, I tried to get a list of all objects by typing:

{
  objective {
    id
  }
}

But this didnt work because of a missing input, so I will try out more stuff...

Is it generally possible to list all entries in graphql withtout specyfing any input?

Thanks

**Comment by zacck** [comment]
@namoscagnm hmmm, I think you are missing the forest for the trees on this one.  What you need to do here is sort the objectives so that the objectives are arranged from the latest on to the earliest one. And in order to do this you would likely add a pattern match like this one 
https://github.com/cambiatus/backend/blob/a6d52d0b2ab083b3f4f2456262f1033faaca73ab/lib/bespiral/commune/commune.ex#L27
and in your pattern match you can run a query that  sorts the objectives something like 
```
def query(Objective, _params) do 
# do your query and sort here 
end 
```

Let  us know if we can explain this further

**Comment by lucca65** [comment]
+1 for @zacck comment

**Comment by namoscagnm** [comment]
@zacck 

Hi, thanks for pointing on the code where the changes will start.

I tried the easiest possible solution given what you proposed, but honestly I would have never been able to navigate to the correct part of the code only from the description.

I have no way of testing if this works or not (it compiles at least), because I do not know how to test it. As I said before i tried it via the API, but it didnt work. Here is my code change:

https://github.com/cambiatus/backend/compare/master...namoscagnm:master

Even if the code is correct, could any of you (@lucca65, @zacck ) tell me how to test it, so I can be more independent next time?

Thank you!

**Comment by zacck** [comment]
Hi @namoscagnm  so  I realized I might have explained this very curtly and perhaps  this was not very helpful to show you what is happening. 
So first off you need to understand we are using dataloader, you can read some of the docs here 
https://github.com/absinthe-graphql/dataloader/blob/0451ee23d618a8e253262a5d7dd423d2e60e666a/lib/dataloader.ex#L8
and also check out this sample explainer project 
https://github.com/absinthe-graphql/absinthe_tutorial/pull/11


## On testing 
You can write a unit test such as where you do the following checks 

1. Insert objectives with random dates 
2. Use your resolver to fetch objectives in the test
3. Ensure that the first objective in the list is the objective with the latest date ( this ensures that your sorting is working) like this assertion here 
https://github.com/cambiatus/backend/blob/a6d52d0b2ab083b3f4f2456262f1033faaca73ab/test/bespiral_web/schema/resolvers/commune_test.exs#L554

Your code is correct, however I dont see why you need the filters parameter as it is  not used, I could be wrong on this though

**Comment by namoscagnm** [comment]
A call would be nice. How can we do it? Via WhatsApp?

**Comment by zacck** [comment]
@lucca65  please share the contact details  ...
