### ISSUE TITLE
Improve Setup documentation

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#92]
Add Wiki documentation to the backend repository:

- Instructions for setting up the dev env
- Adding debug techniques and hints
- Local variables (difference between `dev.exs` and `config.exs`)
- Instructions to don't commit certain files 
- Links for Ecto instructions
- How to setup local ssh tunnels to point local endpoint to staging
- How to dump and restore data for local development

**Comment by victorgdev** [comment]
<img src="https://cambiatus.github.io/assets/logo-cambiatus.png" alt="logo" width="300"> 

# Backend :wave:

### New Organizations for the planet regeneration. Clear Objectives. Impactful Collaboration.

We are an open source platform to empower the creation of new organizations, through Social Currencies on Blockchain.

**For more information checkout:**

- [Wiki](https://cambiatus.github.io/)
- [Blog](https://medium.com/cambiatus)
- [Communities](https://www.cambiatus.com/pilots)
- [FAQs](https://www.cambiatus.com/faq2)

## Table of Contents

- **[General Information](#additional-resources)**
- **[Technologies](#technologies)**
- **[Development Environment Setup](#development-environment-setup)**
- **[Contributing](#contributing)**
- **[Additional Resources](#additional-resources)**
- **[License](#license)**

## General Information

Welcome to the Application that serves as one of the backends for the Cambiatus Ecosystem, One of the backends since this is the one that contains the data in a manner than is easy to index and search.

In the context of the diagram below which is a high level view of how the data flows in our application this application serves as the datastore using a postgress db and as the API using Phoenix running a Graphql Server

### Dataflow Diagram

<img src='https://i.imgur.com/MFfGOe3.png' height='492' alt='Cambiatus Data Flow' />

At a highlevel this is a database that is synced to events on an blockchain which then presents a Graphql API that makes
it simpler to consume the information from the blockhain. At the moment this is a normal database with the the usual
CRUD actions however creation and updating happens as a result of events that trigger writes and updates to our database.

The intention down the line is to make this database a write only database in an Event Sourced structure which will enable us to replay events and give us much more observability.

## Technologies

3.1	- Elixir (Phoenix framework)
3.2	- GraphQL 

- [Ecto](https://hexdocs.pm/ecto/Ecto.html) is database wrapper
- [Absinthe package](https://hexdocs.pm/absinthe/overview.html) GraphQL toolkit for Elixir

3.2.1		- Link to specific guide
3.2.1.1			- Table of Contents
3.2.1.1.1			- GraphQL Basic Intro
3.2.1.1.2			- Sample Queries
3.2.1.1.3			- Sample Mutations
3.2.2		- Absinthe Package -> https://hexdocs.pm/absinthe/overview.html
3.3	- Postgres

## Environment Setup

4.1	- Building and Running the application locally (current set of steps from the setup guide)
4.2	- Specific Setups
4.2.1		- Postgres
4.2.2		- 

## Contributing

5.1	- Intro to basic contributing -> Contributing Guide
5.2	- Tips
5.2.1		- Commits
5.2.1.1			- mix credo for linter testing code consistency
5.2.1.2			- mix format command (IDE format on save config)
5.2.2		- Debugging  techniques on Elixir (https://elixir-lang.org/getting-started/debugging.html)
5.2.3		- Local variables (difference between dev.exs and config.exs)
5.2.4		- How to dump and restore data for local development
5.2.5		- Instructions to don't commit certain files changes (dev.exs and text.exs)

## Additional Resources

6.3   - Here is our [Frontend](https://github.com/cambiatus/frontend) repo if you are interested in contributing and/or learning more about our platform as well

**Comment by lucca65** [comment]
wow this looks amazing! 

I think you can add this as a pull request to the README.md file 

again! looks amazing!
